### ISSUE TITLE
Unexpected token 'export' 

### ISSUE THREAD

**Issue by devdoggy** [hepter/cardon#1]
I wonder what caused the problem and how to fix it

export * from "./withCardon";
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    ... 
    

I do not know what should I do

**Comment by alexandervantrijffel** [comment]
Please share a full example that shows how you try to use cardon
